name: HTML Check

on:
  pull_request:
    paths:
      - '**.htm*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.1 # Requried will all actions
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v8.0.0
      with:
        root: /github/workspace/eclipse.platform.common/bundles
        blacklist: about.html notices.html
        extra: --match *.html  --match *.htm