name: Maven Build
on:
  workflow_call:
    inputs:
      maven-goals:
        description: maven goals to use, defaults to 'clean verify'
        required: false
        default: 'clean verify'
        type: string
      submodules:
        description: |
          Whether to checkout submodules: `true` to checkout submodules or `recursive` to recursively checkout submodules.
          When the `ssh-key` input is not provided, SSH URLs beginning with `git@github.com:` are converted to HTTPS.
          The value is just passed as it is to the github/actions/checkout action: https://github.com/actions/checkout#usage
        type: string
        required: false
        default: 'false'
      extra-setup:
        description: Optional command executed initially to perform additional setup of the build environment
        type: string
        required: false
        default: ''
      mavenVersion:
        description: 'The version of Maven set up'
        type: string
        required: false
        default: '3.9.9'
      without-EF-infra:
        description: 'Whether to run this build without the need for EF-infrastructure (which is currently unavailable).'
        type: boolean
        required: false
        default: true

permissions: {}

env:
  MAVEN_ARGS: >-
    --batch-mode --no-transfer-progress
    ${{ inputs.without-EF-infra && '-Dtycho.version=4.0.12' || '' }}

jobs:
  event_file:
    name: "Upload Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: Event File
        path: ${{ github.event_path }}
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - { name: Linux,   os: ubuntu-latest  }
          - { name: Windows, os: windows-latest }
          - { name: MacOS,   os: macos-13   }
    defaults:
      run: # Run always on bash, because powershell (the Windows default) interprets dots in arguments differently
        shell: bash

    name: Verify ${{ matrix.config.name }}
    steps:
    - name: Enable git longpaths
      run: git config --global core.longpaths true
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
       fetch-depth: 0 # required for jgit timestamp provider to work
       submodules: ${{ inputs.submodules }}
    - name: Set up Java
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: |
          8
          11
          17
          21
        mvn-toolchain-id: |
          JavaSE-1.8
          JavaSE-11
          JavaSE-17
          JavaSE-21
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: ${{ inputs.mavenVersion }}

    - name: Install Maven parent locally
      uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/actions/install-maven-parent-action@master
      if : inputs.without-EF-infra

    - name: Additional setup
      if: inputs.extra-setup
      run: |
        ${{ inputs.extra-setup }}

    - name: Build with Maven
      run: >-
        ${{ runner.os == 'Linux' && 'xvfb-run' || '' }}
        mvn --show-version --update-snapshots --errors
        -Dcompare-version-with-baselines.skip=false
        -Pbree-libs
        -Papi-check
        --fail-at-end
        ${{ inputs.maven-goals }}
    - name: Upload Test Results for ${{ matrix.config.name }}
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: test-results-${{ matrix.config.os }}
        if-no-files-found: warn
        path: |
          ${{ github.workspace }}/**/target/surefire-reports/*.xml
          ${{ github.workspace }}/**/results/**/*.png
