name: Prepare Next Release
on:
  milestone:
    types: [created]

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: contains(github.event.milestone.description, 'Release')
    permissions:
      pull-requests: write
      contents: write
    steps:
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: 3.9.9
    - id: get-release-name
      run: |
        name=$(echo ${{ github.event.milestone.due_on }} | cut -d- -f-2)
        echo "name=$name" >> $GITHUB_OUTPUT
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: master
    - name: Set up JDK
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Update Main Versions
      run: mvn -U -ntp -f eclipse-platform-parent org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=${{ github.event.milestone.title }}.0-SNAPSHOT -Dmodules=../eclipse.platform.releng.prereqs.sdk,../eclipse.platform.releng.tychoeclipsebuilder
    - name: Update Release Versions
      run: mvn -ntp -f eclipse-platform-parent/pom.xml --non-recursive org.eclipse.tycho:tycho-versions-plugin:set-property -Dproperties=releaseVersion,releaseName -DnewReleaseName=${{ steps.get-release-name.outputs.name }} -DnewReleaseVersion=${{ github.event.milestone.title }}
    - name: Create Pull Request for Release ${{ github.event.milestone.title }}
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        commit-message: Prepare Release ${{ github.event.milestone.title }}
        branch: prepare_R${{ github.event.milestone.title }}
        title: Prepare Release ${{ github.event.milestone.title }}
        body: A new Release Milstone was created, please review the changes and merge if appropriate.
        delete-branch: true
        milestone: ${{ github.event.milestone.number }}
        add-paths: |
            eclipse-platform-parent/pom.xml
            eclipse.platform.releng.prereqs.sdk/pom.xml
            eclipse.platform.releng.tychoeclipsebuilder/**/pom.xml
            eclipse.platform.releng.tychoeclipsebuilder/**/*.product

