name: Update Target Platform

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - master
    paths:
      - '**.target'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
        fetch-depth: 0
        ref: master
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: 3.9.7
    - name: Set up JDK
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Update Target Platform
      run: >-
          mvn -ntp -f eclipse.platform.releng.prereqs.sdk 
          org.eclipse.tycho.extras:tycho-version-bump-plugin:4.0.9:update-target
          -DallowMajorUpdates=false
          -Ddiscovery=parent
          -Dmaven.version.rules=update-rules.xml
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
      with:
        commit-message: Update target-platform with latest version
        branch: update_target
        title: Dependency Updates
        body: Please review the changes and merge if appropriate, or cherry pick individual updates.
        delete-branch: true
        draft: false
        token: ${{ secrets.RELENG_BOT_PAT }}
        committer: Eclipse Releng Bot <releng-bot@eclipse.org>
        author: Eclipse Releng Bot <releng-bot@eclipse.org>
        add-paths: |
            **/*.target
