# This workflow will check if the project is currently in a Code-Freeze-Period

name: Verify Code Freeze Period

on:
  workflow_call
  
permissions:
  contents: read

jobs:
  verify-freeze-period:
    runs-on: ubuntu-latest
    steps:
      - name: Checking whether Eclipse project is currently in stabilization/code-freeze period ...
        run: |
          today=$(TZ=UTC date "+%Y-%m-%d")
          tomorrow=$(TZ=UTC date -d "+1 days" "+%Y-%m-%d")
          calId="calendarId=prfk26fdmpru1mptlb06p0jh4s@group.calendar.google.com"
          calURL="https://clients6.google.com/calendar/v3/calendars/group.calendar.google.com/events?${calId}&singleEvents=true&timeZone=UTC&maxResults=250&sanitizeHtml=true&timeMin=${today}T00:00:00Z&timeMax=${tomorrow}T00:00:00Z&key=AIzaSyBNlYH01_9Hc5S1J9vuFmu2nUqBZJNAXxs"
          echo "Querying calendar https://calendar.google.com/calendar/u/0/r?cid=${calId}"
          curl "${calURL}" | grep -i -e "stabilization" -e "signoff" -e "promotion"
          if [[ $? == 0 ]]; then
            echo "::error::Today is a freeze day"
            exit 1 #Exiting with non-0 makes this workflow fail
          fi
          echo "No code freeze today"
        shell: bash {0} # do not fail-fast
